### ISSUE TITLE
Feature request: additional logic to parse domains without https://

### ISSUE THREAD

**Issue by securitybites** [dark-warlord14/JSScanner#2]
Right now the format in the alive.txt file must be `https://domain.com`. It would be nice to be able to have raw domains in the alive.txt file that may be ingested from other tooling.

Request: Allow alive.txt to handle the following content
```
domain.com
happy.domain.com
happy2.domain.com
```

**Comment by dark-warlord14** [comment]
Well you can easily do this using httprobe. I do not have any plans to add features to script that are not related to JavaScript analysis. The whole intention of this script is to gather JavaScript files and make the analysis easier. If you got the domain list you can pass it to httprobe to get the domains in the required format of alive.txt. Let me know what do you think.

**Comment by dark-warlord14** [comment]
Closing this as I don't intend to add the feature. You can easily use httprobe by tomnomnom to do that. Regards.
