### ISSUE TITLE
Add Redirection Option to cURL

### ISSUE THREAD

**Issue by Trio-Musketeers** [dark-warlord14/JSScanner#6]
I have noticed that sometimes when line 67 " curl --connect-timeout 10 --max-time 10 --insecure --silent $js | js-beautify - > db/$n1-$n2/$filename 2> /dev/null"  in script.sh excutes, it might miss downloading the JS files due to 3xx responses from servers,
so I had to add the "-L" option to cURL to fix that issue.
kindly add that option to cURL to avoid that.

Thanks in Advance

**Comment by dark-warlord14** [comment]
Nice catch @Trio-Musketeers. I will add this right now. Thank you for this suggestion.
